name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: "divine.herosite.pro"
        username: "skxgulra"
        password: "Y53sl0P.ky)CV9"
        port: "22999"
        script: |
          echo "${{ secrets.HOST }}"
          echo "${{ secrets.USERNAME }}"
          echo "${{ secrets.KEY }}"
          echo "${{ secrets.PORT }}"
          whoami
          cd /home/skxgulra/domains/beforeafter.co.in/public_html/BAS
          git pull
          ls -al
        
