name: My Workflow

on:
  push:
    branches: [ main ]

jobs:
  my-job:
    runs-on: ubuntu-latest
      env:
        MY_VAL: ${{ secrets.USERNAME }}
      run: |
        import os
        for q in (os.getenv("MY_VAL")):
          print(q)
      shell: python
