name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:          
    - name: Print secrets
      run: |
          echo "${{ secrets.HOST }}"
          echo "${{ secrets.KEY }}"
      env:
          HOST: ${{ secrets.HOST }}
          DATABASE_PASSWORD: ${{ secrets.KEY }}
